version: "3.7"
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    tty: true
    stdin_open: true
    volumes:
      - ./app:/var/www/html

  db:
    image: mysql:5.7
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: mysql000user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
